### PR TITLE
Add rtd theme and xnd.io visual identity

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by skrah** [comment]
Thanks, layout and theme look good to me.  A couple of questions:

```
Running Sphinx v1.6.6
Theme error:
unsupported theme option 'style_external_links' given
```

Do we need that option? If so, I'm fine with requiring a more recent sphinx version.


The most recent version I have also produces some warnings:

```
Running Sphinx v1.7.6
preparing documents... WARNING: unsupported theme option 'vcs_pageview_mode' given
WARNING: unsupported theme option 'relbarbgcolor' given
done
```

For some reason the collapsible prompts have disappeared in my build with the patch.

**Comment by skrah** [comment]
I just see that I'm commenting on a WIP issue, sorry.  I mixed it up with the issue that had a "looks good to me" comment.

**Comment by xmnlab** [comment]
@skrah don't worry and thanks for reviewing that.

actually I am just waiting for feedback about the logo and the name that should I put for this meta package doc (project variable) .. it was ndtypes before .. I changed to plures.

about your comments, I removed `style_external_links`, `vcs_pageview_mode` and `relbarbgcolor`.

I also removed the `View source file` link.

for a next PR I hope to add the github link (I guess I need to figure out how to do that for each project individually)

**Comment by skrah** [comment]
Looks good, thanks.

**Pull request merged**
