### PR TITLE
Added xndtools doc

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by skrah** [comment]
I'm fine with merging the `xndtools ` docs into the combined docs, but let's wait for Pearu to review when he's back (I wasn't quite sure if he wanted them separate or not).

**Comment by xmnlab** [comment]
@skrah Ok!

Just to share, that was the last thing Pearu has commented about that:

```
Ivan, feel free to create a xndtools documentation infrastructure similar to xnd documentations.
My initial view of the xndtools documentation is the following:
1. there are docs for command line tools
2. there are docs for xndtools Python subpackages
3. there are docs for kernel generator file specification - this is perhaps the most important part for kernel generator users
```

**Comment by pearu** [comment]
There is no reason to keep xndtools separate from others, so looks good to me.

**Comment by skrah** [comment]
Ok, great!

**Pull request merged**
