### PR TITLE
Added packaging for xndtools

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by xmnlab** [comment]
I am creating now the conda recipe on xndtools

**Comment by xmnlab** [comment]
https://github.com/plures/xndtools/pull/7

**Comment by xmnlab** [comment]
@pearu @skrah It is done for reviewing! thanks so much!

**Comment by skrah** [comment]
@pearu Is `xndtools` in a good state to be updated in `xnd-all`?  This diff contains many changes that are already in `xndtools`.

`git subtree pull --prefix=xndtools https://github.com/plures/xndtools.git master` should do the trick.

**Comment by xmnlab** [comment]
@skrah 

the command line I used to pull the changes inside the xnd-all was: `git subtree pull --prefix=xndtools https://github.com/plures/xndtools.git` (I just omitted the `master`)

**Comment by pearu** [comment]
yes, xndtools is in good shape.

I guess it would be better to update xndtools (and xnd,ndtypes,gumath) in xnd-all separately from submitting PRs (about docs, packaging,etc) to xnd-all.

**Comment by xmnlab** [comment]
> I guess it would be better to update xndtools (and xnd,ndtypes,gumath) in xnd-all separately from submitting PRs (about docs, packaging,etc) to xnd-all.

@pearu could you provide more details?

**Comment by pearu** [comment]
Sure, @xmnlab: The current PR contains changes to files that are in xndtools/ directory (group 1) and the files that are not in the xndtools/ directory (group 2). 
The first group of files should be merged to xnd-all via `git subtree pull ...` command, these files ought not to be in PR files list. The second group of files should be in this PR.
I presume that this approach would avoid conflicts in cases where PR lifetime is long and meanwhile xndtools gets updated.

**Comment by skrah** [comment]
Pearu, thanks!  I just updated `xndtools` in `xnd-all` this time to see how it would affect the PR.  Normally you should decide of course!

Ivan, I guess you have to update your PR to get rid of the new conflicts.

**Comment by xmnlab** [comment]
@skrah @pearu I updated the source and there is no conflicts anymore. just waiting the green light :)

**Comment by xmnlab** [comment]
@pearu any idea about this error: https://travis-ci.org/plures/xnd-all/jobs/418215635#L2378 ?

**Comment by xmnlab** [comment]
and this one: https://travis-ci.org/plures/xnd-all/jobs/418215636#L2530

**Comment by pearu** [comment]
To fix the second failure, I think stdlib.h needs to be used instead of malloc.h.

About the first failure: ndtypes, xnd. gumath must be installed in order to build xndtools tests.

I'll address these failures in xndtools github, this should fix the failures after xndtools build succeed again.

**Comment by xmnlab** [comment]
I see ... I think the problem is raised in this line: https://github.com/plures/xnd-all/blob/a7728e5efbbb14d1acc07d53f8170116c0a47eec/scripts/conda-install.bat#L24

**Comment by xmnlab** [comment]
^^^ link changed, it seems the problem is on building step.

**Review by pearu — CHANGES_REQUESTED** [review]
LGTM (tested locally).
After updating xndtools subtree in xnd-all, the CI builds should become successful again.
However, many new files (docs, tests) that are not part of this PR, should be removed from this PR. Updating xndtools subtree might partially do that already.

**Comment by xmnlab** [comment]
@pearu 

do you have any idea about this error? https://ci.appveyor.com/project/plures/xnd-all-8n91d/build/1.0.50#L3346

**Comment by pearu** [comment]
I have added xndtools to AppVeyor and fixed all win32 related issues.
Could someone initiate a new AppVeyor build for this PR?

**Comment by xmnlab** [comment]
thanks @pearu 
I updated the PR from master.

**Comment by xmnlab** [comment]
@pearu can we merge this now?

**Review by pearu — APPROVED** [review]

**Comment by skrah** [comment]
Looks good, thanks!

**Pull request merged**
